name       : alsa-lib
version    : 1.2.6.3
release    : 28
source     :
    - ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.2.6.1.tar.bz2 : ad582993d52cdb5fb159a0beab60a6ac57eab0cc1bdf85dc4db6d6197f02333f
    - ftp://ftp.alsa-project.org/pub/lib/alsa-topology-conf-1.2.5.1.tar.bz2 : f7c5bae1545abcd73824bc97f4e72c340e11abea188ba0f1c06f5e0ad776b179
    - ftp://ftp.alsa-project.org/pub/lib/alsa-ucm-conf-1.2.6.3.tar.bz2 : b8a03aa387a624a2f65edc201bf777421190b60529a92087646823afbd96c5cd
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : The ALSA Sound Interface
description: |
    The ALSA Library package contains the ALSA library used by programs (including ALSA Utilities) requiring access to the ALSA sound interface.
patterns   :
    - devel : /usr/share/aclocal/alsa.m4
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/asound.conf $installdir/usr/share/defaults/alsa/asound.conf
    install -dm00755 $installdir/usr/share/alsa/{ucm,ucm2,topology}
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        pushd $installdir/usr/share/alsa/
        tar xvjf $sources/alsa-topology-conf-*.tar.bz2 --strip-components=1
        tar xvjf $sources/alsa-ucm-conf-*.tar.bz2 --strip-components=1
        find -path "*.md" -prune -exec rm -r '{}' \; \
            -or -name "LICENSE" -prune -exec rm -r '{}' \;
        popd
    fi
check      : |
    # Fails on test/lsb so just ignore
    %make check || :
