name       : alsa-lib
version    : 1.1.4.1
release    : 16
source     :
    - ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.4.1.tar.bz2 : 91bb870c14d1c7c269213285eeed874fa3d28112077db061a3af8010d0885b76
license    : LGPL-2.1
component  : multimedia.audio
summary    : The ALSA Sound Interface
patterns   :
    - devel : /usr/share/aclocal/alsa.m4
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    The ALSA Library package contains the ALSA library used by programs (including ALSA Utilities) requiring access to the ALSA sound interface.
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    alsaconfig="--prefix=/usr"
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        alsaconfig="${alsaconfig} --disable-python"
    fi
    %configure ${alsaconfig}
build      : |
    %make
install    : |
    %make_install
    install -D $pkgfiles/asound.conf $installdir/usr/share/defaults/alsa/asound.conf
    %make clean
