name        : alsa-lib
version     : 1.0.27.2
release     : 9
source      :
    - ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.0.27.2.tar.bz2 : 690ed393e7efd4fc7e3a2d2cda5449298ca0c895197e5914e350882012430d19
homepage    : http://www.alsa-project.org
license     : LGPL-2.1
summary     : The ALSA Sound Interface
patterns    :
    - devel: /usr/share/aclocal/alsa.m4
description : |
    The ALSA Library package contains the ALSA library used by programs (including ALSA Utilities) requiring access to the ALSA sound interface.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D $pkgfiles/asound.conf %installroot/etc/asound.conf
