name       : alsa-lib
version    : 1.2.2
release    : 21
source     :
    - ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.2.2.tar.bz2 : d8e853d8805574777bbe40937812ad1419c9ea7210e176f0def3e6ed255ab3ec
    - ftp://ftp.alsa-project.org/pub/lib/alsa-topology-conf-1.2.2.tar.bz2 : b472d6b567c78173bd69543d9cffc9e379c80eb763c3afc8d5b24d5610d19425
    - ftp://ftp.alsa-project.org/pub/lib/alsa-ucm-conf-1.2.2.tar.bz2 : 7ebfd929bc85a51f16fa3c8c4db13faa2ea6ff2b2266fc36d6198bdafe73c40c
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : The ALSA Sound Interface
description: |
    The ALSA Library package contains the ALSA library used by programs (including ALSA Utilities) requiring access to the ALSA sound interface.
patterns   :
    - devel : /usr/share/aclocal/alsa.m4
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/asound.conf $installdir/usr/share/defaults/alsa/asound.conf
    install -dm00755 $installdir/usr/share/alsa/{ucm,ucm2,topology}
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        pushd $installdir/usr/share/alsa/
        tar xvjf $sources/alsa-topology-conf-*.tar.bz2 --strip-components=1
        tar xvjf $sources/alsa-ucm-conf-*.tar.bz2 --strip-components=1
        find -path "*.md" -prune -exec rm -r '{}' \; \
            -or -name "LICENSE" -prune -exec rm -r '{}' \;
        popd
    fi
check      : |
    # Fails on test/lsb so just ignore
    %make check || :
