name       : alsa-lib
version    : 1.1.8
release    : 18
source     :
    - ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.8.tar.bz2 : 3cdc3a93a6427a26d8efab4ada2152e64dd89140d981f6ffa003e85be707aedf
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : The ALSA Sound Interface
description: |
    The ALSA Library package contains the ALSA library used by programs (including ALSA Utilities) requiring access to the ALSA sound interface.
patterns   :
    - devel : /usr/share/aclocal/alsa.m4
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D $pkgfiles/asound.conf $installdir/usr/share/defaults/alsa/asound.conf
check      : |
    %make check
