name       : alsa-lib
version    : 1.1.9
release    : 19
source     :
    - ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.9.tar.bz2 : 488373aef5396682f3a411a6d064ae0ad196b9c96269d0bb912fbdeec94b994b
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : The ALSA Sound Interface
description: |
    The ALSA Library package contains the ALSA library used by programs (including ALSA Utilities) requiring access to the ALSA sound interface.
patterns   :
    - devel : /usr/share/aclocal/alsa.m4
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D $pkgfiles/asound.conf $installdir/usr/share/defaults/alsa/asound.conf
check      : |
    %make check
