name       : alsa-lib
version    : 1.1.5
release    : 17
source     :
    - ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.5.tar.bz2 : f4f68ad3c6da36b0b5241ac3c798a7a71e0e97d51f972e9f723b3f20a9650ae6
license    : LGPL-2.1
component  : multimedia.audio
summary    : The ALSA Sound Interface
patterns   :
    - devel : /usr/share/aclocal/alsa.m4
emul32     : yes
description: |
    The ALSA Library package contains the ALSA library used by programs (including ALSA Utilities) requiring access to the ALSA sound interface.
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    alsaconfig="--prefix=/usr"
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        alsaconfig="${alsaconfig} --disable-python"
    fi
    %configure ${alsaconfig}
build      : |
    %make
install    : |
    %make_install
    install -D $pkgfiles/asound.conf $installdir/usr/share/defaults/alsa/asound.conf
check      : |
    %make check
