name        : alsa-lib
version     : 1.1.1
release     : 11
source     :
    - ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.1.tar.bz2 : 8ac76c3144ed2ed49da7622ab65ac5415205913ccbedde877972383cbc234269
license     : LGPL-2.1
summary     : The ALSA Sound Interface
patterns    :
    - devel: /usr/share/aclocal/alsa.m4
builddeps   :
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
description : |
    The ALSA Library package contains the ALSA library used by programs (including ALSA Utilities) requiring access to the ALSA sound interface.
setup      : |
    alsaconfig="--prefix=/usr"
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        alsaconfig="${alsaconfig} --disable-python"
    fi
    %configure ${alsaconfig}
build      : |
    %make
install    : |
    %make_install
    install -D $pkgfiles/asound.conf %installroot/etc/asound.conf
    %make clean
